### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by Mizuho32** [arkark/latexmk-docker#1]
## Reproduce

```bash
$ sudo docker run --rm -it -v $PWD:/workdir -u $(id -u):$(id -g) arkark/latexmk
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

## Environment
- Manjaro 18.0.4
- Ubuntu18.04

**Comment by arkark** [comment]
Thank you for the report. Fixed it now: https://github.com/ArkArk/latexmk-docker/commit/02162e7635e84469854d46ef8bbf512edd7bce06.

This error occurred because the base image no longer installs bash at https://github.com/Paperist/docker-alpine-texlive-ja/commit/2b43587fb26a013f5bbeb025a10e947db00f9cec.

Please pull `arkark/latexmk` image again, and you will be able to use it :)

**Comment by Mizuho32** [comment]
Great!

**Comment by theking0912** [comment]
replace [go build] to [CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' .]

**Comment by zoispag** [comment]
@theking0912 this was the solution that did the trick for me, expanding on [this post](https://medium.com/@chemidy/create-the-smallest-and-secured-golang-docker-image-based-on-scratch-4752223b7324). Thanks!

**Comment by polarbroadband** [comment]
@theking0912 works to solve this problem while using scratch base image. Thanks!
